/**
 * IN-CLASS ASSESSMENT: Movie API
 * Total: 10 marks
 * Time: 170 minutes
 * 
 * INSTRUCTIONS:
 * Create a simple Movie API using Express, TypeScript, and MongoDB.
 * Complete all 10 tasks marked with TODO comments below.
 * Each task is worth 1 mark.
 * 
 * SETUP & RUN:
 * 1. Install dependencies:
 *    npm install
 * 
 * 2. Create a .env file (copy from .env.example):
 *    DB_CONN_STRING=mongodb+srv://username:password@cluster.mongodb.net/
 *    DB_NAME=movieDB
 *    COLLECTION_NAME=movies
 * 
 * 3. Run the development server:
 *    npm run dev
 *    (Server will start at http://localhost:5000)
 * 
 * 4. Test your endpoints using Postman, Thunder Client, or curl
 * 
 * BEFORE YOU START:
 * - Read through ALL TODO tasks first
 * - Look at the MOVIE SCHEMA below
 * - Reference your previous sushi API code if needed
 * 
 * MOVIE SCHEMA:
 * {
 *   _id: ObjectId (auto-generated by MongoDB)
 *   title: string (required)
 *   director: string (required)
 *   year: number (required, must be between 1900 and current year)
 *   rating: number (required, must be between 1 and 10)
 * }
 */

// ============================================================================
// TODO #1: Import Required Dependencies (1 mark)
// Import: express (including Request, Response types), mongodb (including 
// MongoClient, Db, Collection, ObjectId), and dotenv
// ============================================================================

// YOUR CODE HERE
import express, { Request, Response } from 'express';
import { MongoClient, Db, Collection, ObjectId } from 'mongodb';
import dotenv from 'dotenv';

// ============================================================================
// TODO #2: Create Movie Interface (1 mark)
// Create a TypeScript interface called 'Movie' with the following properties:
// - _id (optional, ObjectId type)
// - title (string)
// - director (string)
// - year (number)
// - rating (number)
// ============================================================================

// YOUR CODE HERE
interface Movie {
    _id?: ObjectId;
    title: string;
    director: string;
    year: number;
    rating: number;
}

// ============================================================================
// TODO #3: Initialize Express App and Environment Variables (1 mark)
// - Configure dotenv to load environment variables
// - Create an Express app instance
// - Set port to 5000
// - Add express.json() middleware to parse JSON bodies
// ============================================================================

// YOUR CODE HERE
dotenv.config();

const app = express();
const PORT = 5000;

app.use(express.json());

// ============================================================================
// TODO #4: Create Database Connection Function (1 mark)
// Create an async function called 'connectToDatabase' that:
// - Gets DB_CONN_STRING, DB_NAME, and COLLECTION_NAME from environment variables
// - Throws an error if any are missing
// - Connects to MongoDB using MongoClient
// - Returns the movies collection
// - Console.logs a success message with database and collection names
// ============================================================================

// YOUR CODE HERE
async function connectToDatabase(): Promise<Collection<Movie>> {
    const dbConnString = process.env.DB_CONN_STRING;
    const dbName = process.env.DB_NAME;
    const collectionName = process.env.COLLECTION_NAME;

    if (!dbConnString || !dbName || !collectionName) {
        throw new Error('Missing required environment variables: DB_CONN_STRING, DB_NAME, COLLECTION_NAME');
    }

    const client = new MongoClient(dbConnString);
    await client.connect();
    
    const db: Db = client.db(dbName);
    const collection: Collection<Movie> = db.collection(collectionName);
    
    console.log(` Connected to database: ${dbName}, collection: ${collectionName}`);
    
    return collection;
}

// ============================================================================
// TODO #5: GET /api/movies - Get All Movies (1 mark)
// Create a GET endpoint that:
// - Fetches all movies from the database using .find({}).toArray()
// - Returns status 200 with the array of movies
// - Handles errors with try-catch and returns status 500 with error message
// ============================================================================

// YOUR CODE HERE
app.get('/api/movies', async (req: Request, res: Response) => {
    try {
        const collection = await connectToDatabase();
        const movies = await collection.find({}).toArray();
        res.status(200).json(movies);
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: 'Failed to fetch movies' });
    }
});

// ============================================================================
// TODO #6: GET /api/movies/:id - Get Movie by ID (1 mark)
// Create a GET endpoint that:
// - Gets the id from route parameters
// - Creates a query using ObjectId with the id
// - Uses .findOne() to get a single movie
// - Returns 404 if movie not found, 200 with movie if found
// - Handles errors with try-catch and returns status 500
// ============================================================================

// YOUR CODE HERE
app.get('/api/movies/:id', async (req: Request, res: Response) => {
    try {
        const id = req.params.id;
        const collection = await connectToDatabase();
        const movie = await collection.findOne({ _id: new ObjectId(id) });
        
        if (!movie) {
            res.status(404).json({ error: 'Movie not found' });
            return;
        }
        
        res.status(200).json(movie);
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: 'Failed to fetch movie' });
    }
});

// ============================================================================
// TODO #7: POST /api/movies - Create New Movie (1 mark)
// Create a POST endpoint that:
// - Gets movie data from request body
// - Uses .insertOne() to add the movie to database
// - Returns status 201 with success message and insertedId if successful
// - Returns status 500 if insertion fails
// - Handles errors appropriately
// ============================================================================

// YOUR CODE HERE
app.post('/api/movies', async (req: Request, res: Response) => {
    try {
        const { title, director, year, rating } = req.body;
        
        const newMovie: Movie = {
            title,
            director,
            year,
            rating
        };
        
        const collection = await connectToDatabase();
        const result = await collection.insertOne(newMovie);
        
        res.status(201).json({ 
            message: 'Movie created successfully', 
            insertedId: result.insertedId 
        });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: 'Failed to create movie' });
    }
});

// ============================================================================
// TODO #8: PUT /api/movies/:id - Update Movie (1 mark)
// Create a PUT endpoint that:
// - Gets id from route parameters and update data from request body
// - Creates a query using ObjectId
// - Uses .updateOne() with $set operator
// - Returns 404 if no movie was modified, 200 with success message if updated
// - Handles errors with try-catch
// ============================================================================

// YOUR CODE HERE
app.put('/api/movies/:id', async (req: Request, res: Response) => {
    try {
        const id = req.params.id;
        const updateData = req.body;
        
        const collection = await connectToDatabase();
        const result = await collection.updateOne(
            { _id: new ObjectId(id) },
            { $set: updateData }
        );
        
        if (result.matchedCount === 0) {
            res.status(404).json({ error: 'Movie not found' });
            return;
        }
        
        res.status(200).json({ message: 'Movie updated successfully' });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: 'Failed to update movie' });
    }
});

// ============================================================================
// TODO #9: DELETE /api/movies/:id - Delete Movie (1 mark)
// Create a DELETE endpoint that:
// - Gets id from route parameters
// - Creates a query using ObjectId
// - Uses .deleteOne() to remove the movie
// - Returns 404 if no movie was deleted, 200 with success message if deleted
// - Handles errors with try-catch
// ============================================================================

// YOUR CODE HERE
app.delete('/api/movies/:id', async (req: Request, res: Response) => {
    try {
        const id = req.params.id;
        
        const collection = await connectToDatabase();
        const result = await collection.deleteOne({ _id: new ObjectId(id) });
        
        if (result.deletedCount === 0) {
            res.status(404).json({ error: 'Movie not found' });
            return;
        }
        
        res.status(200).json({ message: 'Movie deleted successfully' });
    } catch (error) {
        console.error(error);
        res.status(500).json({ error: 'Failed to delete movie' });
    }
});

// ============================================================================
// TODO #10: Start Server with Database Connection (1 mark)
// - Call connectToDatabase() with .then()
// - Store the returned collection in a variable (let moviesCollection)
// - Start the Express server on the specified port inside .then()
// - Console.log server URL when started
// - Catch any database errors, log them, and exit process
// ============================================================================

// YOUR CODE HERE
let moviesCollection: Collection<Movie>;

connectToDatabase()
    .then((collection) => {
        moviesCollection = collection;
        app.listen(PORT, () => {
            console.log(` Server running at http://localhost:${PORT}`);
            console.log(` API endpoints available at http://localhost:${PORT}/api/movies`);
        });
    })
    .catch((error) => {
        console.error(' Failed to connect to database:', error);
        process.exit(1);
    });

// ============================================================================
// TESTING CHECKLIST (for students):
// ============================================================================
// [ ] GET /api/movies - Returns empty array initially
// [ ] POST /api/movies - Creates a new movie with valid data
// [ ] GET /api/movies - Returns array with the created movie
// [ ] GET /api/movies/:id - Returns single movie with valid ID
// [ ] GET /api/movies/:id - Returns 404 with invalid ID
// [ ] PUT /api/movies/:id - Updates movie with valid ID and data
// [ ] DELETE /api/movies/:id - Deletes movie with valid ID
// [ ] All endpoints handle errors properly
// [ ] Server connects to database successfully
// [ ] Code uses proper TypeScript types
